services:
  cvmatch-service:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - cvmatch-db
    restart: unless-stopped
  cvmatch-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"